### ISSUE TITLE
Convert heif byte array  to jpg or png byte array

### ISSUE THREAD

**Issue by pol2095** [0xC0000054/libheif-sharp-samples#2]
Hello,

how to convert a heif byte array  to jpg or png byte array ?

Thanks

**Comment by 0xC0000054** [comment]
The decoder sample shows how to decode HEIF images to PNG.
The [WriteOutputImage](https://github.com/0xC0000054/libheif-sharp-samples/blob/7b033e3012b9d656559891a0fa502c927a93054c/decoder/Program.cs#L315) method is where most of the work is done.

**Comment by pol2095** [comment]
I try to create the libeheif dll using Vcpkg but I obtain a "libeheif.dll" and a "libde265.dll" in "buildtrees" folder, how to integrate libde265.dll in libeheif.dll ?
Thanks

**Comment by pol2095** [comment]
It work, thanks.

**Comment by pol2095** [comment]
Is-it possible to get a rgba or argb byte array instead of jpeg or png ?

**Comment by 0xC0000054** [comment]
> Is-it possible to get a rgba or argb byte array instead of jpeg or png ?

Yes, you can use something like the following:

```c#
static byte[] GetHeifImageBytes(HeifImage heifImage)
{
	HeifPlaneData planeData = heifImage.GetPlane(HeifChannel.Interleaved);
	
	byte[] pixels = new byte[planeData.Stride * planeData.Height];		
	
    Marshal.Copy(planeData.Scan0, pixels, 0, pixels.Length);
	
	return pixels;
}
```
