### ISSUE TITLE
Avif lossless quality

### ISSUE THREAD

**Issue by hieudole** [0xC0000054/libheif-sharp-samples#4]
Thanks for your the samples you created. I'm able to integrate libheif-sharp with another image processor library.

When I run the sample encoder with -L option (lossless compression), the output image has lower quality and the size is smaller than the default lossy compression (which has quality = 50). I think this lossless option does not work correctly, even the code reached the line:

encoder.SetLossless(true);
// Lossless encoding requires YUV 4:4:4 chroma.
encoder.SetParameter("chroma", "444");

Is this due to a bug in libheif or do I need to set parameter to the encoder? I'm using rav1e as avif encoder.

Thank you!

**Comment by 0xC0000054** [comment]
> Is this due to a bug in libheif or do I need to set parameter to the encoder?

That is a bug in the encoder sample, apparently libheif requires the lossy quality to be set when using lossless encoding.
I will be fixing this in LibHeifSharp, in the mean time you can change the encoder sample to call `SetLossyQuality` before calling `SetLossless`.
